#!/usr/bin/env bash
# HMRAY production installer — 4 prompts only (English).
# Telegram bot token / admin chat ID are configured later in Admin Panel → Settings.

set -euo pipefail

INSTALL_DIR="${HMRAY_INSTALL_DIR:-/opt/hmray}"
SRC_DIR="${HMRAY_SRC_DIR:-/opt/hmray/src}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
COMPOSE_SRC="${REPO_ROOT}/deploy/docker-compose/docker-compose.yml"
CADDY_SRC="${REPO_ROOT}/deploy/caddy/Caddyfile"
LOG_FILE="${INSTALL_DIR}/install.log"
TTY="${HMRAY_TTY:-/dev/tty}"

log() {
  echo "[$(date -Iseconds)] $*" | tee -a "$LOG_FILE" 2>/dev/null || echo "[$(date -Iseconds)] $*"
}

die() {
  log "ERROR: $*"
  exit 1
}

require_root() {
  if [[ "${EUID:-$(id -u)}" -ne 0 ]]; then
    die "Run as root: sudo $0"
  fi
}

prompt() {
  local var_name="$1"
  local question="$2"
  local default="${3:-}"
  local value=""
  local input="$TTY"
  [[ -r "$input" ]] || input="/dev/stdin"
  if [[ -n "$default" ]]; then
    read -r -p "${question} [${default}]: " value <"$input"
    value="${value:-$default}"
  else
    read -r -p "${question}: " value <"$input"
    while [[ -z "$value" ]]; do
      read -r -p "${question} (required): " value <"$input"
    done
  fi
  printf -v "$var_name" '%s' "$value"
}

prompt_secret() {
  local var_name="$1"
  local question="$2"
  local value=""
  local input="$TTY"
  [[ -r "$input" ]] || input="/dev/stdin"
  read -r -s -p "${question}: " value <"$input"
  echo
  while [[ -z "$value" ]]; do
    read -r -s -p "${question} (required): " value <"$input"
    echo
  done
  printf -v "$var_name" '%s' "$value"
}

random_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
  else
    head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n'
  fi
}

load_env_value() {
  local key="$1"
  local file="${INSTALL_DIR}/.env"
  [[ -f "$file" ]] || return 1
  grep -E "^${key}=" "$file" | head -1 | cut -d= -f2- | sed 's/^"//;s/"$//'
}

install_docker() {
  if command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
    log "Docker and Compose already installed."
    return 0
  fi

  log "Installing Docker Engine and Compose plugin..."
  apt-get update -qq
  apt-get install -y ca-certificates curl gnupg
  install -m 0755 -d /etc/apt/keyrings
  if [[ ! -f /etc/apt/keyrings/docker.gpg ]]; then
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
  fi
  echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
    $(. /etc/os-release && echo "${VERSION_CODENAME:-jammy}") stable" \
    > /etc/apt/sources.list.d/docker.list
  apt-get update -qq
  apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  systemctl enable --now docker
  log "Docker installed."
}

# Postgres only reads POSTGRES_PASSWORD on first init. A new .env password
# cannot unlock an existing volume — wipe postgres data on fresh config.
reset_postgres_volume() {
  log "Resetting Postgres volume for new database password..."
  mkdir -p "$INSTALL_DIR"
  cd "$INSTALL_DIR"
  if [[ -f docker-compose.yml && -f .env ]]; then
    compose down --remove-orphans >/dev/null 2>&1 || true
  fi
  # Project name defaults to directory name (hmray → hmray_postgres_data)
  local vol
  while IFS= read -r vol; do
    [[ -n "$vol" ]] || continue
    log "Removing volume: $vol"
    docker volume rm -f "$vol" >/dev/null 2>&1 || true
  done < <(docker volume ls -q | grep -E '(^|_)postgres_data$' || true)
}

write_env_file() {
  local jwt_secret bot_secret panel_url
  jwt_secret="$(random_secret)"
  bot_secret="$(random_secret)"
  panel_url="https://${DOMAIN}:${PANEL_PORT}"

  umask 077
  cat > "${INSTALL_DIR}/.env" <<EOF
# Generated by HMRAY install.sh
NODE_ENV=production
TZ=${TIMEZONE}

POSTGRES_USER=hmray
POSTGRES_PASSWORD=${DB_PASSWORD}
POSTGRES_DB=hmray
DATABASE_URL=postgresql://hmray:${DB_PASSWORD}@postgres:5432/hmray?schema=public
REDIS_URL=redis://redis:6379

JWT_SECRET=${jwt_secret}
JWT_EXPIRES_IN=7d

ADMIN_USERNAME=${ADMIN_USERNAME}
ADMIN_PASSWORD=${ADMIN_PASSWORD}
ADMIN_EMAIL=admin@${DOMAIN}
ADMIN_DISPLAY_NAME="HMRAY Owner"

# Telegram is configured later in Admin Panel → Settings
TELEGRAM_BOT_TOKEN=
ADMIN_TELEGRAM_CHAT_ID=
BOT_INTERNAL_SECRET=${bot_secret}
BOT_MODE=polling
WEBHOOK_URL=

UPLOAD_DIR=/app/uploads
MAX_UPLOAD_BYTES=5242880
QUOTE_PUBLIC_BASE_URL=${panel_url}
PUBLIC_URL=${panel_url}
ADMIN_PUBLIC_URL=${panel_url}
CORS_ORIGINS=${panel_url}
NEXT_PUBLIC_API_URL=/api

# Pre-built images from GitHub Container Registry
HMRAY_IMAGE_PREFIX=ghcr.io/neoauroraproject/hmrayexpo
HMRAY_IMAGE_TAG=latest

PORT=4000
PANEL_PORT=${PANEL_PORT}
WORKER_PORT=4001
DOMAIN=${DOMAIN}
ACME_EMAIL=${ACME_EMAIL}
EOF
  chmod 600 "${INSTALL_DIR}/.env"
  log "Wrote ${INSTALL_DIR}/.env (secrets are not logged)."
}

compose() {
  docker compose -f "${INSTALL_DIR}/docker-compose.yml" --env-file "${INSTALL_DIR}/.env" "$@"
}

pull_or_build_images() {
  log "Pulling pre-built images from GHCR (fast path)..."
  if compose pull; then
    log "Images pulled successfully."
    return 0
  fi

  log "GHCR pull failed — falling back to local source build (slow)..."
  local build_yml="${INSTALL_DIR}/docker-compose.build.yml"
  if [[ ! -f "$build_yml" ]]; then
    die "Missing ${build_yml} and GHCR pull failed."
  fi
  export DOCKER_BUILDKIT=1
  export COMPOSE_DOCKER_CLI_BUILD=1
  if ! docker compose \
      -f "${INSTALL_DIR}/docker-compose.yml" \
      -f "$build_yml" \
      --env-file "${INSTALL_DIR}/.env" \
      build; then
    log "Retrying local build with npmmirror..."
    NPM_REGISTRY=https://registry.npmmirror.com docker compose \
      -f "${INSTALL_DIR}/docker-compose.yml" \
      -f "$build_yml" \
      --env-file "${INSTALL_DIR}/.env" \
      build
  fi
}

run_migrations() {
  log "Running database migrations..."
  compose exec -T api hmray-db migrate \
    || compose exec -T -w /app api sh /usr/local/bin/hmray-db migrate \
    || compose exec -T -w /app api sh -c '
         BIN=$(find /app -path "*/node_modules/prisma/build/index.js" | head -n1)
         test -n "$BIN"
         node "$BIN" migrate deploy --schema=/app/packages/database/prisma/schema.prisma
       '
}

run_seed() {
  log "Seeding database..."
  compose exec -T api hmray-db seed \
    || compose exec -T -w /app api sh /usr/local/bin/hmray-db seed \
    || compose exec -T -w /app api sh -c '
         if [ -x /app/node_modules/.bin/tsx ]; then
           /app/node_modules/.bin/tsx /app/packages/database/prisma/seed.ts
         else
           node --import tsx /app/packages/database/prisma/seed.ts
         fi
       '
}

finish_ok() {
  local panel_url="https://${DOMAIN}:${PANEL_PORT}"
  local user_name="${ADMIN_USERNAME:-owner}"
  echo
  echo "============================================"
  echo " INSTALL SUCCESS"
  echo "============================================"
  echo " Admin panel: ${panel_url}"
  echo " Username:    ${user_name}"
  echo
  echo " Next steps:"
  echo "  1) Open the admin panel and log in"
  echo "  2) Settings → Telegram → set Bot Token + Chat ID"
  echo "============================================"
  log "Install completed successfully."
}

finish_fail() {
  echo
  echo "============================================"
  echo " INSTALL INCOMPLETE"
  echo "============================================"
  echo " Containers may be running, but a late step failed."
  echo " Check logs:"
  echo "   cd /opt/hmray && docker compose --env-file .env logs --tail=100 api"
  echo "============================================"
}

wait_for_api() {
  local attempt=0
  log "Waiting for API health..."
  while [[ $attempt -lt 60 ]]; do
    if compose exec -T api sh -c \
      "node -e \"require('http').get('http://127.0.0.1:4000/health',r=>process.exit(r.statusCode===200?0:1)).on('error',()=>process.exit(1))\"" \
      >/dev/null 2>&1; then
      return 0
    fi
    attempt=$((attempt + 1))
    sleep 5
  done
  die "API did not become healthy in time. Check: docker compose -f ${INSTALL_DIR}/docker-compose.yml logs api"
}

wait_for_tls() {
  local attempt=0
  local url="https://${DOMAIN}:${PANEL_PORT}/health"
  log "Waiting for Let's Encrypt on ${url} (DNS A record + firewall tcp/80 required)..."
  while [[ $attempt -lt 24 ]]; do
    if curl -sf --max-time 10 "$url" >/dev/null 2>&1; then
      log "TLS ready: ${url}"
      return 0
    fi
    attempt=$((attempt + 1))
    if [[ $((attempt % 4)) -eq 0 ]]; then
      compose logs --tail=15 caddy || true
    fi
    sleep 5
  done
  log "WARNING: certificate not ready yet. Open tcp/80 and confirm DNS points here, then: docker compose --env-file .env logs caddy"
  return 1
}

run_healthchecks() {
  log "Running health checks..."
  bash "${INSTALL_DIR}/scripts/healthcheck.sh"
}

main() {
  require_root

  echo "=== HMRAY Installer ==="
  echo "Install directory: ${INSTALL_DIR}"
  echo "Telegram bot settings will be configured in the Admin Panel after install."
  echo

  install_docker

  mkdir -p "${INSTALL_DIR}/scripts" "${INSTALL_DIR}/backups"
  touch "$LOG_FILE"
  chmod 600 "$LOG_FILE"

  [[ -d "$SRC_DIR" ]] || die "Source not found at ${SRC_DIR}. Run the setup launcher first."
  [[ -f "$COMPOSE_SRC" ]] || die "Missing ${COMPOSE_SRC}"
  [[ -f "$CADDY_SRC" ]] || die "Missing ${CADDY_SRC}"

  REUSE_ENV=false
  if [[ -f "${INSTALL_DIR}/.env" ]]; then
    reuse_answer=""
    read -r -p "Existing .env found. Reuse it? [Y/n]: " reuse_answer <"${TTY}"
    reuse_answer="${reuse_answer:-Y}"
    if [[ "$reuse_answer" =~ ^[Yy]$ ]]; then
      REUSE_ENV=true
      log "Reusing existing .env"
      set -a
      # shellcheck disable=SC1091
      source "${INSTALL_DIR}/.env"
      set +a
      DOMAIN="${DOMAIN:-$(load_env_value DOMAIN || true)}"
      PANEL_PORT="${PANEL_PORT:-$(load_env_value PANEL_PORT || echo 8443)}"
    fi
  fi

  if [[ "$REUSE_ENV" == false ]]; then
    echo
    echo "Answer 4 questions:"
    echo
    prompt DOMAIN "1/4 Domain (DNS A record must point here)"
    prompt PANEL_PORT "2/4 HTTPS panel port" "8443"
    prompt ADMIN_USERNAME "3/4 Admin username" "owner"
    prompt_secret ADMIN_PASSWORD "4/4 Admin password"
    echo

    TIMEZONE="Asia/Tehran"
    ACME_EMAIL="admin@${DOMAIN}"
    DB_PASSWORD="$(random_secret)"

    write_env_file
    # Must wipe BEFORE start — old volume keeps the previous password forever
    reset_postgres_volume
  fi

  log "Copying compose files..."
  cp "$COMPOSE_SRC" "${INSTALL_DIR}/docker-compose.yml"
  if [[ -f "${REPO_ROOT}/deploy/docker-compose/docker-compose.build.yml" ]]; then
    cp "${REPO_ROOT}/deploy/docker-compose/docker-compose.build.yml" "${INSTALL_DIR}/docker-compose.build.yml"
  fi
  cp "$CADDY_SRC" "${INSTALL_DIR}/Caddyfile"
  cp "${REPO_ROOT}/deploy/scripts/healthcheck.sh" "${INSTALL_DIR}/scripts/healthcheck.sh"
  cp "${REPO_ROOT}/deploy/scripts/backup-db.sh" "${INSTALL_DIR}/scripts/backup-db.sh"
  chmod +x "${INSTALL_DIR}/scripts/"*.sh

  # Ensure compose context ./src resolves under /opt/hmray (fallback builds)
  if [[ "$(readlink -f "$SRC_DIR" 2>/dev/null || echo "$SRC_DIR")" != "$(readlink -f "${INSTALL_DIR}/src" 2>/dev/null || echo "${INSTALL_DIR}/src")" ]]; then
    rm -rf "${INSTALL_DIR}/src"
    ln -sfn "$SRC_DIR" "${INSTALL_DIR}/src"
  fi

  pull_or_build_images

  log "Starting services..."
  compose up -d --remove-orphans

  wait_for_api

  if ! run_migrations; then
    finish_fail
    die "Database migration failed."
  fi

  if [[ "$REUSE_ENV" == false ]]; then
    if ! run_seed; then
      finish_fail
      die "Database seed failed."
    fi
  fi

  run_healthchecks || log "Healthcheck reported issues (bot may wait until Telegram is configured)."

  # Prefer values from current shell / .env
  DOMAIN="${DOMAIN:-$(load_env_value DOMAIN || true)}"
  PANEL_PORT="${PANEL_PORT:-$(load_env_value PANEL_PORT || echo 8443)}"
  ADMIN_USERNAME="${ADMIN_USERNAME:-$(load_env_value ADMIN_USERNAME || echo owner)}"

  wait_for_tls || log "Continue once DNS/port 80 are fixed — then restart: cd /opt/hmray && docker compose --env-file .env restart caddy"

  finish_ok
}

main "$@"
