#!/usr/bin/env bash
# HMRAY production installer — idempotent Ubuntu setup wizard.
# Usage: sudo ./install.sh   OR   curl -fsSL .../install.sh | sudo bash

set -euo pipefail

INSTALL_DIR="${HMRAY_INSTALL_DIR:-/opt/hmray}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
COMPOSE_SRC="${REPO_ROOT}/deploy/docker-compose/docker-compose.yml"
CADDY_SRC="${REPO_ROOT}/deploy/caddy/Caddyfile"
LOG_FILE="${INSTALL_DIR}/install.log"

# ─── Helpers ─────────────────────────────────────────────────────────────────

log() {
  echo "[$(date -Iseconds)] $*" | tee -a "$LOG_FILE" 2>/dev/null || echo "[$(date -Iseconds)] $*"
}

die() {
  log "ERROR: $*"
  exit 1
}

require_root() {
  if [[ "${EUID:-$(id -u)}" -ne 0 ]]; then
    die "Run as root: sudo $0"
  fi
}

prompt() {
  local var_name="$1"
  local question="$2"
  local default="${3:-}"
  local value=""
  if [[ -n "$default" ]]; then
    read -r -p "${question} [${default}]: " value
    value="${value:-$default}"
  else
    read -r -p "${question}: " value
    while [[ -z "$value" ]]; do
      read -r -p "${question} (required): " value
    done
  fi
  printf -v "$var_name" '%s' "$value"
}

prompt_secret() {
  local var_name="$1"
  local question="$2"
  local value=""
  read -r -s -p "${question}: " value
  echo
  while [[ -z "$value" ]]; do
    read -r -s -p "${question} (required): " value
    echo
  done
  printf -v "$var_name" '%s' "$value"
}

prompt_optional_secret() {
  local var_name="$1"
  local question="$2"
  local value=""
  read -r -s -p "${question} (Enter to skip): " value
  echo
  printf -v "$var_name" '%s' "$value"
}

random_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
  else
    head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n'
  fi
}

load_env_value() {
  local key="$1"
  local file="${INSTALL_DIR}/.env"
  [[ -f "$file" ]] || return 1
  grep -E "^${key}=" "$file" | head -1 | cut -d= -f2- | sed 's/^"//;s/"$//'
}

install_docker() {
  if command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
    log "Docker and Compose plugin already installed."
    return 0
  fi

  log "Installing Docker Engine and Compose plugin (Ubuntu apt)…"
  apt-get update -qq
  apt-get install -y ca-certificates curl gnupg
  install -m 0755 -d /etc/apt/keyrings
  if [[ ! -f /etc/apt/keyrings/docker.gpg ]]; then
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
  fi
  echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
    $(. /etc/os-release && echo "${VERSION_CODENAME:-jammy}") stable" \
    > /etc/apt/sources.list.d/docker.list
  apt-get update -qq
  apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  systemctl enable --now docker
  log "Docker installed."
}

write_env_file() {
  local jwt_secret bot_secret panel_port_https admin_url
  jwt_secret="$(random_secret)"
  bot_secret="$(random_secret)"
  panel_port_https="https://${DOMAIN}:${PANEL_PORT}"

  umask 077
  cat > "${INSTALL_DIR}/.env" <<EOF
# Generated by HMRAY install.sh — $(date -Iseconds)
NODE_ENV=production
TZ=${TIMEZONE}

# ─── Install / images ───────────────────────────────────────
HMRAY_IMAGE_PREFIX=${HMRAY_IMAGE_PREFIX}
HMRAY_IMAGE_TAG=${HMRAY_IMAGE_TAG}
POSTGRES_USER=hmray
POSTGRES_PASSWORD=${DB_PASSWORD}
POSTGRES_DB=hmray

# ─── Database & cache ───────────────────────────────────────
DATABASE_URL=postgresql://hmray:${DB_PASSWORD}@postgres:5432/hmray?schema=public
REDIS_URL=redis://redis:6379

# ─── Auth ───────────────────────────────────────────────────
JWT_SECRET=${jwt_secret}
JWT_EXPIRES_IN=7d

# ─── Seed owner account ─────────────────────────────────────
ADMIN_USERNAME=${ADMIN_USERNAME}
ADMIN_PASSWORD=${ADMIN_PASSWORD}
ADMIN_EMAIL=admin@${DOMAIN}
ADMIN_DISPLAY_NAME=HMRAY Owner

# ─── Telegram ───────────────────────────────────────────────
TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
ADMIN_TELEGRAM_CHAT_ID=${ADMIN_TELEGRAM_CHAT_ID}
BOT_INTERNAL_SECRET=${bot_secret}
BOT_MODE=webhook
WEBHOOK_URL=${panel_port_https}/api/bot/webhook

# ─── Uploads & URLs ─────────────────────────────────────────
UPLOAD_DIR=/app/uploads
MAX_UPLOAD_BYTES=5242880
QUOTE_PUBLIC_BASE_URL=${panel_port_https}
PUBLIC_URL=${panel_port_https}
ADMIN_PUBLIC_URL=${panel_port_https}
CORS_ORIGINS=${panel_port_https}

# ─── Ports & proxy ──────────────────────────────────────────
PORT=4000
PANEL_PORT=${PANEL_PORT}
WORKER_PORT=4001
DOMAIN=${DOMAIN}
ACME_EMAIL=${ACME_EMAIL}
EOF
  chmod 600 "${INSTALL_DIR}/.env"
  log "Wrote ${INSTALL_DIR}/.env (secrets are not logged)."
}

run_migrations() {
  log "Running database migrations…"
  docker compose -f "${INSTALL_DIR}/docker-compose.yml" --env-file "${INSTALL_DIR}/.env" \
    exec -T api sh -c \
    'npx prisma migrate deploy --schema=/app/packages/database/prisma/schema.prisma'
}

run_seed() {
  log "Seeding database (owner admin + defaults)…"
  docker compose -f "${INSTALL_DIR}/docker-compose.yml" --env-file "${INSTALL_DIR}/.env" \
    exec -T api sh -c \
    'node --import tsx /app/packages/database/prisma/seed.ts'
}

wait_for_api() {
  local attempt=0
  log "Waiting for API health…"
  while [[ $attempt -lt 30 ]]; do
    if docker compose -f "${INSTALL_DIR}/docker-compose.yml" --env-file "${INSTALL_DIR}/.env" \
      exec -T api sh -c \
      "node -e \"require('http').get('http://127.0.0.1:4000/health',r=>process.exit(r.statusCode===200?0:1)).on('error',()=>process.exit(1))\"" \
      >/dev/null 2>&1; then
      return 0
    fi
    attempt=$((attempt + 1))
    sleep 5
  done
  die "API did not become healthy in time."
}

run_healthchecks() {
  log "Running post-install health checks…"
  bash "${INSTALL_DIR}/scripts/healthcheck.sh"
}

# ─── Main ────────────────────────────────────────────────────────────────────

main() {
  require_root

  echo "=== HMRAY Platform Installer ==="
  echo "Install directory: ${INSTALL_DIR}"
  echo

  install_docker

  mkdir -p "${INSTALL_DIR}/scripts" "${INSTALL_DIR}/backups"
  touch "$LOG_FILE"
  chmod 600 "$LOG_FILE"

  [[ -f "$COMPOSE_SRC" ]] || die "Missing ${COMPOSE_SRC} — run from the repository checkout."
  [[ -f "$CADDY_SRC" ]] || die "Missing ${CADDY_SRC}"

  # Idempotent: reuse or overwrite existing .env
  REUSE_ENV=false
  if [[ -f "${INSTALL_DIR}/.env" ]]; then
    read -r -p ".env already exists at ${INSTALL_DIR}/.env. Reuse it? [Y/n]: " reuse_answer
    reuse_answer="${reuse_answer:-Y}"
    if [[ "$reuse_answer" =~ ^[Yy]$ ]]; then
      REUSE_ENV=true
      log "Reusing existing .env"
      # shellcheck disable=SC1091
      set -a
      source "${INSTALL_DIR}/.env"
      set +a
      DOMAIN="${DOMAIN:-$(load_env_value DOMAIN || true)}"
      PANEL_PORT="${PANEL_PORT:-$(load_env_value PANEL_PORT || echo 8443)}"
    fi
  fi

  if [[ "$REUSE_ENV" == false ]]; then
    prompt DOMAIN "Public domain (DNS must point to this server)"
    prompt PANEL_PORT "Admin panel TLS port" "8443"
    prompt ADMIN_USERNAME "Admin username" "owner"
    prompt_secret ADMIN_PASSWORD "Admin password"
    prompt_secret TELEGRAM_BOT_TOKEN "Telegram Bot Token"
    prompt ADMIN_TELEGRAM_CHAT_ID "Admin Telegram Chat ID"
    prompt TIMEZONE "Timezone" "Asia/Tehran"
    prompt_secret DB_PASSWORD "PostgreSQL password"
    prompt ACME_EMAIL "ACME/Let's Encrypt email" "admin@${DOMAIN}"
    prompt HMRAY_IMAGE_PREFIX "GHCR image prefix (owner/repo path without tag)" "ghcr.io/neoauroraproject/hmrayexpo"
    prompt HMRAY_IMAGE_TAG "Image tag to deploy" "latest"
    prompt_optional_secret GHCR_TOKEN "GHCR pull token"

    write_env_file
  else
    GHCR_TOKEN=""
    prompt_optional_secret GHCR_TOKEN "GHCR pull token (Enter to skip)"
    HMRAY_IMAGE_PREFIX="${HMRAY_IMAGE_PREFIX:-$(load_env_value HMRAY_IMAGE_PREFIX || echo ghcr.io/your-org/hmray)}"
    HMRAY_IMAGE_TAG="${HMRAY_IMAGE_TAG:-$(load_env_value HMRAY_IMAGE_TAG || echo latest)}"
  fi

  log "Copying docker-compose and Caddyfile…"
  cp "$COMPOSE_SRC" "${INSTALL_DIR}/docker-compose.yml"
  cp "$CADDY_SRC" "${INSTALL_DIR}/Caddyfile"
  cp "${REPO_ROOT}/deploy/scripts/healthcheck.sh" "${INSTALL_DIR}/scripts/healthcheck.sh"
  cp "${REPO_ROOT}/deploy/scripts/backup-db.sh" "${INSTALL_DIR}/scripts/backup-db.sh"
  chmod +x "${INSTALL_DIR}/scripts/"*.sh

  if [[ -n "${GHCR_TOKEN:-}" ]]; then
    log "Logging in to GHCR…"
    echo "${GHCR_TOKEN}" | docker login ghcr.io -u hmray-installer --password-stdin >/dev/null
  fi

  log "Pulling images and starting services…"
  docker compose -f "${INSTALL_DIR}/docker-compose.yml" --env-file "${INSTALL_DIR}/.env" pull
  docker compose -f "${INSTALL_DIR}/docker-compose.yml" --env-file "${INSTALL_DIR}/.env" up -d

  wait_for_api

  if [[ "$REUSE_ENV" == false ]]; then
    run_migrations
    run_seed
  else
    log "Skipping migrate/seed because existing .env was reused (run update.sh to migrate)."
    run_migrations || log "Migration step failed — check logs."
  fi

  run_healthchecks

  panel_url="https://${DOMAIN}:${PANEL_PORT}"
  echo
  echo "════════════════════════════════════════════════════════"
  echo " HMRAY is ready."
  echo " Admin panel: ${panel_url}"
  echo " API health:  ${panel_url}/health"
  echo " Install dir: ${INSTALL_DIR}"
  echo "════════════════════════════════════════════════════════"
  log "Install completed successfully."
}

main "$@"
