export enum RequestStatus {
  REQUESTED = "REQUESTED",
  UNDER_REVIEW = "UNDER_REVIEW",
  QUOTED = "QUOTED",
  EXPIRED = "EXPIRED",
  CANCELLED = "CANCELLED",
}

export enum QuoteStatus {
  DRAFT = "DRAFT",
  SENT = "SENT",
  ACCEPTED = "ACCEPTED",
  REJECTED = "REJECTED",
  EXPIRED = "EXPIRED",
  SUPERSEDED = "SUPERSEDED",
}

export enum PaymentStatus {
  PENDING = "PENDING",
  UNDER_REVIEW = "UNDER_REVIEW",
  CONFIRMED = "CONFIRMED",
  REJECTED = "REJECTED",
  REFUNDED = "REFUNDED",
}

// Channel where payment was registered
export enum PaymentSource {
  BOT = "BOT",
  WEB = "WEB",
  SUPPORT = "SUPPORT",
  ADMIN = "ADMIN",
}

export enum OrderStatus {
  CONFIRMED = "CONFIRMED",
  PAID = "PAID",
  PURCHASING = "PURCHASING",
  PURCHASED = "PURCHASED",
  IN_TRANSIT_TO_OMAN = "IN_TRANSIT_TO_OMAN",
  ARRIVED_OMAN = "ARRIVED_OMAN",
  QUALITY_CHECK = "QUALITY_CHECK",
  READY_FOR_IRAN = "READY_FOR_IRAN",
  SHIPPING_TO_IRAN = "SHIPPING_TO_IRAN",
  ARRIVED_IRAN = "ARRIVED_IRAN",
  DOMESTIC_DELIVERY = "DOMESTIC_DELIVERY",
  DELIVERED = "DELIVERED",
  CANCELLED = "CANCELLED",
  RETURN_REQUESTED = "RETURN_REQUESTED",
  RETURN_PROCESSING = "RETURN_PROCESSING",
  REFUND_PENDING = "REFUND_PENDING",
  REFUNDED = "REFUNDED",
}

export enum RequestType {
  TEMU = "TEMU",
  EXTERNAL_STORE = "EXTERNAL_STORE",
  MANUAL = "MANUAL",
}

export enum InspectionType {
  FULL_OPEN = "FULL_OPEN",
  VISUAL_ONLY = "VISUAL_ONLY",
  SEALED = "SEALED",
}

export enum AdminRole {
  OWNER = "OWNER",
  ADMIN = "ADMIN",
  SUPPORT = "SUPPORT",
  FINANCE = "FINANCE",
  OPERATOR = "OPERATOR",
}

export enum NotificationEvent {
  NEW_REQUEST = "NEW_REQUEST",
  QUOTE_ACCEPTED = "QUOTE_ACCEPTED",
  PAYMENT_SUBMITTED = "PAYMENT_SUBMITTED",
  PAYMENT_RECEIPT_UPLOADED = "PAYMENT_RECEIPT_UPLOADED",
  SUPPORT_MESSAGE = "SUPPORT_MESSAGE",
  REFUND_REQUESTED = "REFUND_REQUESTED",
  NEW_ORDER = "NEW_ORDER",
  ORDER_READY = "ORDER_READY",
  QUALITY_ISSUE = "QUALITY_ISSUE",
  TEMU_BATCH_READY = "TEMU_BATCH_READY",
  QUOTE_SENT = "QUOTE_SENT",
  QUOTE_EXPIRED = "QUOTE_EXPIRED",
  PAYMENT_CONFIRMED = "PAYMENT_CONFIRMED",
  PAYMENT_REJECTED = "PAYMENT_REJECTED",
}

export enum Currency {
  TOMAN = "TOMAN",
  OMR = "OMR",
  USD = "USD",
  USDT = "USDT",
}

export enum RequestItemStatus {
  ACTIVE = "ACTIVE",
  REMOVED = "REMOVED",
  UNAVAILABLE = "UNAVAILABLE",
  PRICED = "PRICED",
}

export enum NoteVisibility {
  CUSTOMER = "CUSTOMER",
  INTERNAL = "INTERNAL",
}

export enum TemuBatchStatus {
  OPEN = "OPEN",
  READY = "READY",
  PURCHASING = "PURCHASING",
  PURCHASED = "PURCHASED",
  CANCELLED = "CANCELLED",
}

export enum PurchaseMode {
  NORMAL = "NORMAL",
  INSTANT = "INSTANT",
}

export enum ReturnStatus {
  RETURN_REQUESTED = "RETURN_REQUESTED",
  ADMIN_REVIEW = "ADMIN_REVIEW",
  RETURN_APPROVED = "RETURN_APPROVED",
  RETURN_TO_SELLER = "RETURN_TO_SELLER",
  REFUND = "REFUND",
  REJECTED = "REJECTED",
}

export enum BroadcastStatus {
  DRAFT = "DRAFT",
  SENDING = "SENDING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
}

export enum ShipmentStatus {
  PENDING = "PENDING",
  IN_TRANSIT = "IN_TRANSIT",
  ARRIVED = "ARRIVED",
  DELIVERED = "DELIVERED",
  CANCELLED = "CANCELLED",
}

export enum TicketStatus {
  OPEN = "OPEN",
  PENDING = "PENDING",
  RESOLVED = "RESOLVED",
  CLOSED = "CLOSED",
}
